### PR TITLE
Update some deps and make changes for notistack 3.0

### PR DESCRIPTION
**Pull request by dakaza98**
Some deps did not require any change but notistack requires some changes. There are some formatting changes that make it difficult to see all the changes but I'll explain them here. I hade to add the Components prop in app.tsx and in snackbarcontent.tsx i had to change some of the props. I also remove the custom useSnackbar hook since it's customizations are no longer needed

### CODE REVIEW

**Review by albinantti — APPROVED** [review]
It looks good to me, although it should be rebased to 079882eb0f72a0cd57bc149e59c14bd61bdb333a as it seems that this merge would re-add the import react-statements to every file. It's also  bit unfortunate that it seems to change formatting for a lot of files.

Approved provided you look into this

**Review by albinantti — CHANGES_REQUESTED** [review]
See above comment

**Comment by chwallen** [comment]
The easiest would be to not introduce the formatting changes. They are all introduced by 2f77766.

**Comment by dakaza98** [comment]
@albinantti I have updated the branch now to not include `import react from "react"`

**Review by albinantti — CHANGES_REQUESTED** [review]
Looks good, but could you re-save SnackbarContent.tsx and App.tsx using .editorconfig? Primarily in regards to the 2-space indentation which we don't use elsewhere, this doesn't feel like a it should be a 3k line change pull request

**Review by albinantti — APPROVED** [review]
ty

**Pull request merged**
